# Server configuration
server.port=8080

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/planify_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Disable Liquibase and Redis
# ===============================
spring.liquibase.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.planify=DEBUG
